### ISSUE TITLE
Does not build with OpenSSL 3

### ISSUE THREAD

**Issue by mohd-akram** [toddsundsted/openssl_ext#1]
I came here from ktistec, I get this error while trying to build it:

```
Undefined symbols for architecture x86_64:
  "_EVP_PKEY_size", referenced from:
      _*OpenSSL::RSA@OpenSSL::PKey#max_encrypt_size:Int32 in O-penS-S-L-5858R-S-A-.o
```

The function is `EVP_PKEY_get_size` in OpenSSL 3.

**Comment by toddsundsted** [comment]
this is probably a simple fix. i'm trying to figure out a path to installing openssl 3 for testing

**Comment by toddsundsted** [comment]
eh, the solution was right under my nose...

**Comment by mohd-akram** [comment]
Thanks! I can confirm that it works. Hopefully the dependency can be updated in ktistec too.
